name: SignTracker
main: de.rubingrube.SignTracker.Main
version: 3.0
description: "tracks and logs players sign placements."
author: OverCrave
api-version: 1.19
commands:
  signtracker:
    description: "Base Command"
    usage: /signtracker
  signtracker reload:
    description: "Reload Command"
    usage: /signtracker reload
  signtracker resetconfig:
    description: "Reset Config Command"
    usage: /signtracker resetconfig
