name: SignTracker
main: com.rubygenix.SignTracker.Main
version: 2.2
description: "tracks and logs players sign placements."
author: Rubyblex
api-version: 1.16
commands:
  signtracker:
    description: "Base Command"
    usage: /signtracker
  signtracker reload:
    description: "Reload Command"
    usage: /signtracker reload
  signtracker resetconfig:
    description: "Reset Config Command"
    usage: /signtracker resetconfig
