name: SignTracker
main: net.overcrave.signtracker.Main
version: 2.0
api-version: 1.14
description: "tracks and logs players sign placements."
author: OverCrave
commands:
  signtracker:
    description: "Base Command"
    usage: /signtracker
  signtracker reload:
    description: "Reload Command"
    usage: /signtracker reload
  signtracker resetconfig:
    description: "Reset Config Command"
    usage: /signtracker resetconfig
